import re, json

# 1) 解析现有 overlay.js 的 DICT
ov = open("overlay.js", encoding="utf-8").read()
m = re.search(r"var DICT = (\{.*?\});", ov, re.S)
block = m.group(1)
DICT = {}
# 形如 'Key': 'Val' 或 "Key": "Val" 或 Key: 'Val'
for km in re.finditer(r"""([\"']?)([^'"{},\s][^'{}]*?)\1\s*:\s*([\"'])(.*?)\3""", block, re.S):
    k = km.group(2).strip()
    v = km.group(4)
    DICT[k] = v
print("解析现有 DICT:", len(DICT))

# 2) 新增翻译（EN -> ZH）
NEW = {
 "Access denied": "访问被拒绝",
 "Access denied - check server permissions": "访问被拒绝 - 请检查服务器权限",
 "Add files, prompts, tools or MCP Servers": "添加文件、提示词、工具或 MCP 服务器",
 "Add to favorites": "添加到收藏",
 "Agentic summary": "智能体摘要",
 "Agentic turns (LLM calls)": "智能体轮次（LLM 调用）",
 "All MCP server connections failed": "所有 MCP 服务器连接失败",
 "All conversations deleted": "已删除所有对话",
 "Ask anything...": "随便问问…",
 "Assistant message with actions": "带操作的助手消息",
 "Audio recording not supported": "不支持音频录制",
 "Avg speed": "平均速度",
 "Bearer <token>": "Bearer <令牌>",
 "Binary content": "二进制内容",
 "Browser Tools": "浏览器工具",
 "Bulk actions for selected conversations": "对已选对话的批量操作",
 "Capabilities exchanged successfully": "能力交换成功",
 "Chat completion request was aborted": "聊天补全请求已中止",
 "Choose working directory": "选择工作目录",
 "Clear search": "清除搜索",
 "Cleared all user overrides": "已清除所有用户覆盖",
 "Click for model details": "点击查看模型详情",
 "Close Sidebar": "关闭侧边栏",
 "Code copied to clipboard": "代码已复制到剪贴板",
 "Code incomplete": "代码不完整",
 "Collapse navigation": "收起导航",
 "Connecting to server...": "正在连接服务器…",
 "Connection Error": "连接错误",
 "Connection error - please try again": "连接错误 - 请重试",
 "Context usage": "上下文占用",
 "Continue generation error:": "继续生成错误：",
 "Conversation deleted": "对话已删除",
 "Conversation exported": "对话已导出",
 "Conversation forked": "对话已分叉",
 "Conversation pin toggled": "对话置顶状态已切换",
 "Copied to clipboard": "已复制到剪贴板",
 "Copy code": "复制代码",
 "Copy content": "复制内容",
 "Copy mermaid syntax": "复制 mermaid 语法",
 "Copy model name": "复制模型名称",
 "Copy model name to clipboard": "复制模型名称到剪贴板",
 "Copy model path to clipboard": "复制模型路径到剪贴板",
 "Copy svg source": "复制 svg 源码",
 "Copy to clipboard": "复制到剪贴板",
 "Custom Headers": "自定义请求头",
 "Custom JSON": "自定义 JSON",
 "Custom Tools": "自定义工具",
 "Delete All": "全部删除",
 "Delete Conversation": "删除对话",
 "Delete Message": "删除消息",
 "Delete all conversations": "删除所有对话",
 "Delete conversation?": "删除对话？",
 "Delete selected": "删除所选",
 "Deselect all": "取消全选",
 "Diagram incomplete": "图表不完整",
 "Discard changes?": "放弃更改？",
 "Download SVG": "下载 SVG",
 "Download content": "下载内容",
 "Edit system message...": "编辑系统消息…",
 "Edit your message...": "编辑你的消息…",
 "Enter fork name": "输入分叉名称",
 "Enter your API key...": "输入你的 API 密钥…",
 "Enter {name}": "输入{name}",
 "Error checking API key:": "检查 API 密钥时出错：",
 "Error converting PDF to images:": "将 PDF 转为图片时出错：",
 "Error converting PDF to text:": "将 PDF 转为文本时出错：",
 "Error fetching server properties:": "获取服务器属性时出错：",
 "Error in sendMessage:": "sendMessage 出错：",
 "Error parsing JSON chunk:": "解析 JSON 片段时出错：",
 "Error processing file": "处理文件时出错",
 "Exit bulk selection mode": "退出批量选择模式",
 "Expand navigation": "展开导航",
 "Export conversations": "导出对话",
 "Export failed:": "导出失败：",
 "Export selected": "导出所选",
 "Export settings": "导出设置",
 "Failed to add system prompt:": "添加系统提示词失败：",
 "Failed to attach resources:": "附加资源失败：",
 "Failed to attach template resource:": "附加模板资源失败：",
 "Failed to bulk delete conversations:": "批量删除对话失败：",
 "Failed to bulk export conversations:": "批量导出对话失败：",
 "Failed to bulk toggle pin:": "批量切换置顶失败：",
 "Failed to connect to server": "连接服务器失败",
 "Failed to continue agentic turn:": "继续智能体轮次失败：",
 "Failed to continue message:": "继续消息失败：",
 "Failed to convert HEIC to PNG:": "将 HEIC 转为 PNG 失败：",
 "Failed to convert SVG to PNG:": "将 SVG 转为 PNG 失败：",
 "Failed to convert WebP to PNG:": "将 WebP 转为 PNG 失败：",
 "Failed to convert audio to WAV:": "将音频转为 WAV 失败：",
 "Failed to copy code": "复制代码失败",
 "Failed to copy code:": "复制代码失败：",
 "Failed to copy mermaid syntax:": "复制 mermaid 语法失败：",
 "Failed to copy svg source:": "复制 svg 源码失败：",
 "Failed to copy to clipboard": "复制到剪贴板失败",
 "Failed to copy to clipboard:": "复制到剪贴板失败：",
 "Failed to delete all conversations:": "删除所有对话失败：",
 "Failed to delete conversation:": "删除对话失败：",
 "Failed to delete conversations": "删除对话失败",
 "Failed to delete conversations:": "删除对话失败：",
 "Failed to delete message:": "删除消息失败：",
 "Failed to edit assistant message:": "编辑助手消息失败：",
 "Failed to edit message with branching:": "分支编辑消息失败：",
 "Failed to edit user message:": "编辑用户消息失败：",
 "Failed to export conversations": "导出对话失败",
 "Failed to export settings": "导出设置失败",
 "Failed to export settings:": "导出设置失败：",
 "Failed to fetch": "获取失败",
 "Failed to fetch router models:": "获取路由模型失败：",
 "Failed to fork conversation": "分叉对话失败",
 "Failed to fork conversation:": "分叉对话失败：",
 "Failed to generate response:": "生成回复失败：",
 "Failed to get 2D canvas context.": "获取 2D 画布上下文失败。",
 "Failed to get 2D context from canvas": "从画布获取 2D 上下文失败",
 "Failed to import conversations": "导入对话失败",
 "Failed to import settings": "导入设置失败",
 "Failed to import settings:": "导入设置失败：",
 "Failed to initialize conversations:": "初始化对话失败：",
 "Failed to initialize settings store:": "初始化设置存储失败：",
 "Failed to load conversation:": "加载对话失败：",
 "Failed to load conversations": "加载对话失败",
 "Failed to load conversations:": "加载对话失败：",
 "Failed to load image.": "加载图片失败。",
 "Failed to load model": "加载模型失败",
 "Failed to load model:": "加载模型失败：",
 "Failed to load models": "加载模型失败",
 "Failed to load resource content": "加载资源内容失败",
 "Failed to load tools": "加载工具失败",
 "Failed to open file picker": "打开文件选择器失败",
 "Failed to open file picker:": "打开文件选择器失败：",
 "Failed to parse custom parameters:": "解析自定义参数失败：",
 "Failed to parse file:": "解析文件失败：",
 "Failed to process markdown:": "处理 markdown 失败：",
 "Failed to read file": "读取文件失败",
 "Failed to read file.": "读取文件失败。",
 "Failed to read resource": "读取资源失败",
 "Failed to regenerate message:": "重新生成消息失败：",
 "Failed to render mermaid diagram:": "渲染 mermaid 图表失败：",
 "Failed to save config to localStorage:": "保存配置到 localStorage 失败：",
 "Failed to save partial response:": "保存部分回复失败：",
 "Failed to select model:": "选择模型失败：",
 "Failed to send message:": "发送消息失败：",
 "Failed to start recording:": "开始录制失败：",
 "Failed to stop recording:": "停止录制失败：",
 "Failed to toggle conversation pin:": "切换对话置顶失败：",
 "Failed to unload model": "卸载模型失败",
 "Failed to update conversation name:": "更新对话名称失败：",
 "Failed to update conversation timestamp:": "更新对话时间戳失败：",
 "Failed to update message:": "更新消息失败：",
 "Failed to update pin state": "更新置顶状态失败",
 "File reading error": "文件读取错误",
 "Fork Conversation": "分叉对话",
 "Fork conversation": "分叉对话",
 "Found: thinking conditional": "已找到：思维链条件",
 "Generated tokens": "已生成令牌",
 "Generation speed": "生成速度",
 "Generation time": "生成时间",
 "Go to start": "回到开头",
 "Header name": "请求头名称",
 "Hugging Face": "Hugging Face",
 "Image processing requires a vision model": "图像处理需要视觉模型",
 "Images require a vision-capable model": "图片需要支持视觉的模型",
 "Import conversations": "导入对话",
 "Import failed:": "导入失败：",
 "Import settings": "导入设置",
 "Initializing connection to server...": "正在初始化与服务器的连接…",
 "Invalid URL format": "URL 格式无效",
 "Invalid data URL format.": "数据 URL 格式无效。",
 "Invalid data: missing conversation": "数据无效：缺少对话",
 "Invalid data: no conversations to export": "数据无效：没有可导出的对话",
 "Invalid settings data: missing config": "设置数据无效：缺少配置",
 "Invalid settings file: missing config": "设置文件无效：缺少配置",
 "JSON Schema": "JSON 模式",
 "Keep editing": "继续编辑",
 "Keeps only k top tokens.": "仅保留概率最高的 k 个令牌。",
 "LLM stream error": "LLM 流错误",
 "List files": "列出文件",
 "Listing available tools...": "正在列出可用工具…",
 "Loading draft": "正在加载草稿",
 "Loading model": "正在加载模型",
 "Loading projector": "正在加载投影层",
 "Loading weights": "正在加载权重",
 "MCP Prompt": "MCP 提示词",
 "MCP Prompt message with actions": "带操作的 MCP 提示词消息",
 "MCP Resource": "MCP 资源",
 "MCP server configuration is missing url": "MCP 服务器配置缺少 url",
 "Maximum image resolution (megapixels)": "最大图片分辨率（百万像素）",
 "MediaRecorder error:": "MediaRecorder 错误：",
 "Message copied to clipboard": "消息已复制到剪贴板",
 "Missing required parameter: code": "缺少必需参数：code",
 "Model default": "模型默认",
 "Model information": "模型信息",
 "More actions": "更多操作",
 "More allow options": "更多允许选项",
 "Name reported by the server": "服务器报告的名称",
 "New Chat": "新建对话",
 "Next version": "下一版本",
 "No MCP prompts available": "无可用 MCP 提示词",
 "No PDF file available for conversion": "无可用 PDF 文件进行转换",
 "No active conversation": "没有活动对话",
 "No active recording to stop": "没有正在进行的录制可停止",
 "No chat template available": "无可用聊天模板",
 "No code element found in wrapper": "包装器中未找到代码元素",
 "No conversations found in file": "文件中未找到对话",
 "No conversations to delete": "没有可删除的对话",
 "No conversations to export": "没有可导出的对话",
 "No conversations yet": "还没有对话",
 "No custom headers configured.": "未配置自定义请求头。",
 "No items configured.": "未配置项目。",
 "No items found": "未找到项目",
 "No matching command": "无匹配命令",
 "No matching files or folders": "无匹配的文件或文件夹",
 "No response body": "无响应内容",
 "No results found": "未找到结果",
 "No thinking patterns found": "未找到思维链模式",
 "No wrapper found": "未找到包装器",
 "Not available": "不可用",
 "Not found": "未找到",
 "Not supported by current model": "当前模型不支持",
 "Open Sidebar": "打开侧边栏",
 "Open command picker": "打开命令选择器",
 "Open conversations": "打开对话",
 "Open picker": "打开选择器",
 "Open prompt picker": "打开提示词选择器",
 "Open website": "打开网站",
 "Operation was aborted": "操作已中止",
 "PDF File": "PDF 文件",
 "PDF Page {index + 1}": "PDF 第 {index + 1} 页",
 "PDF parsing as images enabled!": "PDF 已启用图片解析！",
 "Parse error": "解析错误",
 "Paste token here": "在此粘贴令牌",
 "Pending user message": "待发送的用户消息",
 "Pin all": "全部置顶",
 "Please enter a server URL first.": "请先输入服务器 URL。",
 "Please select a model first": "请先选择模型",
 "Preparing response...": "正在准备回复…",
 "Preview code": "预览代码",
 "Preview diagram": "预览图表",
 "Preview svg": "预览 svg",
 "Preview {language}": "预览 {language}",
 "Preview {name}": "预览 {name}",
 "Prompt processing speed": "提示词处理速度",
 "Prompt processing time": "提示词处理时间",
 "Prompt tokens evaluated": "已评估的提示词令牌",
 "Record audio, type a message": "录制音频，或输入消息",
 "Recording error:": "录制错误：",
 "Recording failed": "录制失败",
 "Refresh resources": "刷新资源",
 "Remove from favorites": "从收藏中移除",
 "Remove item": "移除项目",
 "Request failed": "请求失败",
 "Request timed out": "请求超时",
 "Reset to defaults": "重置为默认",
 "Reset view": "重置视图",
 "Reset working directory": "重置工作目录",
 "Resource already attached": "资源已附加",
 "Resource content": "资源内容",
 "Retry loading model": "重试加载模型",
 "Sandbox execution aborted": "沙箱执行已中止",
 "Save only": "仅保存",
 "Scroll left": "向左滚动",
 "Scroll right": "向右滚动",
 "Scroll to bottom": "滚动到底部",
 "Search conversations...": "搜索对话…",
 "Search models...": "搜索模型…",
 "Search prompts...": "搜索提示词…",
 "Search resources...": "搜索资源…",
 "Select all": "全选",
 "Selected model is not available": "所选模型不可用",
 "Send immediately": "立即发送",
 "Sending initialize request...": "正在发送初始化请求…",
 "Sent as Image": "以图片发送",
 "Sent as Text": "以文本发送",
 "Server Error": "服务器错误",
 "Server error - check server logs": "服务器错误 - 请检查服务器日志",
 "Server is not running or unreachable": "服务器未运行或无法连接",
 "Server not found - check server address": "未找到服务器 - 请检查服务器地址",
 "Server temporarily unavailable": "服务器暂时不可用",
 "Server unavailable": "服务器不可用",
 "Set working directory": "设置工作目录",
 "Set working directory to": "将工作目录设置为",
 "Set working directory to ...": "将工作目录设置为…",
 "Settings exported": "设置已导出",
 "Settings imported successfully": "设置导入成功",
 "Show full path in mentions": "在 @ 提及中显示完整路径",
 "Something went wrong": "出了点问题",
 "Speculative decoding enabled": "已启用推测解码",
 "Start recording": "开始录制",
 "Start typing to see results": "开始输入以查看结果",
 "Stop recording": "停止录制",
 "Stream error": "流错误",
 "Streaming error:": "流式错误：",
 "System message": "系统消息",
 "System message with actions": "带操作的系统消息",
 "TCP Timeout": "TCP 超时",
 "Text message content": "文本消息内容",
 "This action cannot be undone.": "此操作不可撤销。",
 "Timeout for individual MCP tool calls.": "单个 MCP 工具调用的超时时间。",
 "Toggle mermaid source": "切换 mermaid 源码",
 "Toggle source": "切换源码",
 "Toggle svg source": "切换 svg 源码",
 "Tokens generated": "已生成令牌",
 "Tool calls": "工具调用",
 "Tool calls executed": "已执行的工具调用",
 "Tool execution rate": "工具执行速率",
 "Tool execution time": "工具执行时间",
 "Tool execution was denied by the user.": "工具执行被用户拒绝。",
 "Total matches: N": "匹配总数：N",
 "Total time (LLM + tools)": "总时间（LLM + 工具）",
 "Total tokens generated": "已生成令牌总数",
 "Type a message": "输入消息",
 "Type a message...": "输入消息…",
 "URL is required": "URL 为必填项",
 "Unable to load models:": "无法加载模型：",
 "Unavailable for mixed state selection": "混合状态选择时不可用",
 "Unknown File": "未知文件",
 "Unknown Model": "未知模型",
 "Unknown error": "未知错误",
 "Unknown error executing prompt": "执行提示词时发生未知错误",
 "Unknown error occurred": "发生未知错误",
 "Unknown server error": "未知服务器错误",
 "Unload model": "卸载模型",
 "Unpin all": "全部取消置顶",
 "Untitled conversation": "未命名对话",
 "User message with actions": "带操作用户消息",
 "User overrides after sync:": "同步后的用户覆盖：",
 "Video files require a video-capable model": "视频文件需要支持视频的模型",
 "View All": "查看全部",
 "Waiting for tokens...": "正在等待令牌…",
 "Wants Authorization": "需要授权",
 "Web UI": "网页界面",
 "WebSocket connection closed": "WebSocket 连接已关闭",
 "Worker creation failed:": "Worker 创建失败：",
 "Zoom in": "放大",
 "Zoom out": "缩小",
}

# 3) 合并
before = len(DICT)
for k, v in NEW.items():
    DICT[k] = v
print("新增条目:", len(NEW), "合并后:", len(DICT))

# 4) 写回 overlay.js（保留原有运行时逻辑，仅替换 DICT）
runtime = ov[:ov.index("var DICT =")]  # 前缀（IIFE 开头 + 'use strict'）
# 重新构造 DICT 字面量
lines = ["(function(){", "  'use strict';", "  var DICT = {"]
for k in sorted(DICT.keys()):
    kv = DICT[k].replace("\\", "\\\\").replace("'", "\\'")
    kk = k.replace("\\", "\\\\").replace("'", "\\'")
    lines.append("    '%s': '%s'," % (kk, kv))
lines.append("  };")
# 取原文件 DICT 之后的内容（运行时逻辑）
after = ov[ov.index("var DICT =") + len("var DICT =") + ov[ov.index("var DICT ="):].index("{")+1:]
# 更稳妥：直接截取原文件从 "  var lang" 开始的部分
idx = ov.index("  var lang")
after_part = ov[idx:]
out = "\n".join(lines) + "\n" + after_part
open("overlay.js", "w", encoding="utf-8").write(out)
print("已写出 overlay.js, 总字节:", len(out))
